Repository equinor/design-system, pull requests merged in 2020-08, with the labels that each got.

#483 Fix file upload and link buttons
  libraries/core-react/src/Button/Button.jsx
Labels: bug-fix

#479 Trigger Tooltip on disabled elements
  apps/storybook-react/stories/Tooltip.stories.jsx
  libraries/core-react/src/Button/Button.jsx
  libraries/core-react/src/Tooltip/Tooltip.jsx
Labels: bug-fix

#406 Pagination
  apps/storybook-react/stories/Pagination.stories.jsx
  libraries/core-react/src/Pagination/Pagination.jsx
  libraries/core-react/src/Pagination/Pagination.test.jsx
  libraries/core-react/src/Pagination/Pagination.tokens.js
  libraries/core-react/src/Pagination/PaginationItem.jsx
  libraries/core-react/src/Pagination/index.js
  libraries/core-react/src/Pagination/paginationControl.js
  libraries/core-react/src/index.js
Labels: react

#502 add route and meta-title to changelog
  apps/storefront/docs/updates/release-information/changelog.mdx
Labels: bug-fix

#519 Removed size prop in Button Icon Story
  apps/storybook-react/stories/Button.stories.jsx
Labels: bug-fix, documentation

#527 Typescript eslint
  .eslintrc.js
  .eslintrc.yaml
  libraries/core-react/azure-pipelines.yml
  libraries/core-react/tsconfig.json
  libraries/icons/azure-pipelines.yml
  libraries/icons/tsconfig.json
  libraries/tokens/azure-pipelines.yml
  libraries/tokens/tsconfig.json
  package.yaml
  pnpm-lock.yaml
  tsconfig.base.json
  tsconfig.eslint.json
Labels: typescript
