Repository equinor/design-system, pull requests merged in 2021-01, with the labels that each got.

#988 🐛 Stuck hover effects on touch devices
  libraries/core-react/src/components/SelectionControls/Checkbox/Input.tsx
  libraries/core-react/src/components/SelectionControls/Radio/Radio.tsx
  libraries/core-react/src/components/SelectionControls/Switch/InputWrapper.tsx
Labels: bug-fix

#991 📝 Updated Icon story with controls
  apps/storybook-react/stories/Icon.stories.tsx
Labels: bug-fix

#996 📝 Document required TS version
  README.md
  apps/storefront/docs/getting-started/developers/introduction.mdx
  libraries/core-react/README.md
  libraries/icons/README.md
  libraries/tokens/README.md
Labels: bug-fix

#1002 Remove addon-knobs
  apps/storybook-react/.storybook/main.js
  apps/storybook-react/package.json
  apps/storybook-react/pnpm-lock.yaml
  apps/storybook-react/stories-disabled/Divider/Divider.docs.mdx
Labels: storybook

#1050 🐛 Fix pnpm version
  apps/storefront/Dockerfile
  apps/storefront/package.json
Labels: bug-fix

#1083 Update sub component names
  libraries/core-react/src/components/Accordion/index.ts
  libraries/core-react/src/components/Banner/index.ts
  libraries/core-react/src/components/Card/index.ts
  libraries/core-react/src/components/List/index.ts
  libraries/core-react/src/components/Menu/index.tsx
  libraries/core-react/src/components/Popover/index.ts
  libraries/core-react/src/components/Snackbar/index.ts
  libraries/core-react/src/components/Tabs/index.ts
  libraries/core-react/stories/components/Accordion.stories.tsx
  libraries/core-react/stories/components/Avatar.stories.tsx
  libraries/core-react/stories/components/Banner.stories.tsx
  libraries/core-react/stories/components/Breadcrumbs.stories.tsx
  libraries/core-react/stories/components/Button.stories.tsx
  libraries/core-react/stories/components/Card.stories.tsx
  libraries/core-react/stories/components/Chips.stories.tsx
  libraries/core-react/stories/components/Circular.stories.tsx
  libraries/core-react/stories/components/Dialog.stories.tsx
  libraries/core-react/stories/components/Divider.stories.tsx
  libraries/core-react/stories/components/Dots.stories.tsx
  libraries/core-react/stories/components/Icon.stories.tsx
  libraries/core-react/stories/components/Linear.stories.tsx
  libraries/core-react/stories/components/Lists.stories.tsx
  libraries/core-react/stories/components/Menu.stories.tsx
  libraries/core-react/stories/components/MultiSelect.stories.tsx
  libraries/core-react/stories/components/NativeSelect.stories.tsx
  libraries/core-react/stories/components/Pagination.stories.tsx
  libraries/core-react/stories/components/Popover.stories.tsx
  libraries/core-react/stories/components/Scrim.stories.tsx
  libraries/core-react/stories/components/Search.stories.tsx
  libraries/core-react/stories/components/SelectionControls.Checkbox.stories.tsx
  libraries/core-react/stories/components/SelectionControls.Radio.stories.tsx
  libraries/core-react/stories/components/SelectionControls.Switch.stories.tsx
  libraries/core-react/stories/components/SideSheet.stories.tsx
  libraries/core-react/stories/components/SingleSelect.stories.tsx
  libraries/core-react/stories/components/Slider.stories.tsx
  libraries/core-react/stories/components/Snackbar.stories.tsx
  libraries/core-react/stories/components/Star.stories.tsx
  libraries/core-react/stories/components/Table.stories.tsx
  libraries/core-react/stories/components/TableOfContents.stories.tsx
  libraries/core-react/stories/components/Tabs.stories.tsx
  libraries/core-react/stories/components/TextField.stories.tsx
  libraries/core-react/stories/components/Tooltip.stories.tsx
  libraries/core-react/stories/components/TopBar.stories.tsx
Labels: react
